#!/usr/bin/env bash
# Secret management for the loop (v3): sops + age — free, account-less, encrypted at rest.
# Scopes (one encrypted env file each, see lib.sh secret_file/secret_exec):
#   worker : the Claude credential (CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY)
#   gate   : test-time secrets injected ONLY into the deterministic gate checks
#   codex  : OPENAI_API_KEY for the second-opinion reviewer (skip if you use `codex login`)
#
#   ./control/secrets.sh init [--if-needed]   one-time: age key + .sops.yaml (idempotent)
#   ./control/secrets.sh edit <scope>         edit a scope's secrets via `sops edit` (no
#                                             plaintext file ever touches disk)
#   ./control/secrets.sh status               per-scope: present/decryptable + auth mode
#   ./control/secrets.sh migrate --yes        one-shot v2.2 migration: encrypt legacy plaintext
#                                             secret.env / secret.gate.env, then shred them
set -euo pipefail
source "$(dirname "$0")/lib.sh"

SCOPES="worker gate codex"

need_tools() {
  command -v sops >/dev/null 2>&1 || die "sops not found. Install: https://github.com/getsops/sops/releases (single binary)."
  command -v age-keygen >/dev/null 2>&1 || die "age not found. Install: apt install age  (or https://github.com/FiloSottile/age)."
}

age_recipient() {
  # Public recipient from the key file (safe to print/commit).
  grep -oE 'age1[0-9a-z]+' "$SOPS_AGE_KEY_FILE" 2>/dev/null | head -1
}

ensure_key() {
  if [ ! -f "$SOPS_AGE_KEY_FILE" ]; then
    mkdir -p "$(dirname "$SOPS_AGE_KEY_FILE")"
    age-keygen -o "$SOPS_AGE_KEY_FILE"
    chmod 600 "$SOPS_AGE_KEY_FILE"
    echo "secrets: new age keypair at $SOPS_AGE_KEY_FILE (chmod 600). BACK IT UP — losing it loses every encrypted secret."
  fi
  chmod 600 "$SOPS_AGE_KEY_FILE" 2>/dev/null || true
}

ensure_sops_yaml() {
  local rec; rec="$(age_recipient)"
  [ -n "$rec" ] || die "no age recipient found in $SOPS_AGE_KEY_FILE"
  if [ ! -f "$CONFIG_DIR/.sops.yaml" ]; then
    cat > "$CONFIG_DIR/.sops.yaml" <<EOF
# AUTO-GENERATED by \`loop secrets init\`. Holds only the PUBLIC age recipient (safe to commit).
creation_rules:
  - path_regex: secret\\..*\\.sops\\.env\$
    age: $rec
EOF
    echo "secrets: wrote $CONFIG_DIR/.sops.yaml (recipient $rec)"
  fi
}

scope_template() {
  case "$1" in
    worker) echo "$CONTROL_DIR/secret.worker.env.example" ;;
    gate)   echo "$CONTROL_DIR/secret.gate.env.example" ;;
    codex)  echo "$CONTROL_DIR/secret.codex.env.example" ;;
    *) die "unknown scope '$1' (worker|gate|codex)" ;;
  esac
}

cmd_init() {
  local if_needed=0; [ "${1:-}" = "--if-needed" ] && if_needed=1
  [ "$SECRET_BACKEND" = sops ] || { echo "secrets: SECRET_BACKEND=$SECRET_BACKEND — init only manages the sops backend."; return 0; }
  if [ "$if_needed" = 1 ] && [ -f "$CONFIG_DIR/.sops.yaml" ] && [ -f "$SOPS_AGE_KEY_FILE" ]; then return 0; fi
  need_tools; ensure_key; ensure_sops_yaml
  echo "secrets: ready. Add your credential with:  loop secrets edit worker"
}

cmd_edit() {
  local scope="${1:?usage: secrets.sh edit <worker|gate|codex>}"
  [ "$SECRET_BACKEND" = sops ] || die "edit manages the sops backend only (SECRET_BACKEND=$SECRET_BACKEND)."
  need_tools; ensure_key; ensure_sops_yaml
  local f; f="$(secret_file "$scope")"
  if [ ! -f "$f" ]; then
    # Seed from the scope's documented template, encrypting in one pass (no plaintext on disk).
    local tpl; tpl="$(scope_template "$scope")"
    [ -f "$tpl" ] || tpl=/dev/null
    ( cd "$CONFIG_DIR" && SOPS_AGE_KEY_FILE="$SOPS_AGE_KEY_FILE" \
        sops encrypt --input-type dotenv --output-type dotenv "$tpl" > "$f" ) \
      || die "could not create $f"
    echo "secrets: created $f from template."
  fi
  ( cd "$CONFIG_DIR" && SOPS_AGE_KEY_FILE="$SOPS_AGE_KEY_FILE" sops edit "$f" )
}

cmd_status() {
  echo "secrets: backend=$SECRET_BACKEND  key=$SOPS_AGE_KEY_FILE $( [ -f "$SOPS_AGE_KEY_FILE" ] && echo '(present)' || echo '(MISSING)')"
  local s f
  for s in $SCOPES; do
    f="$(secret_file "$s")"
    if [ ! -f "$f" ]; then
      printf '  %-7s absent   (%s)\n' "$s" "$f"
      continue
    fi
    if [ "$SECRET_BACKEND" = sops ]; then
      if SOPS_AGE_KEY_FILE="$SOPS_AGE_KEY_FILE" sops decrypt "$f" >/dev/null 2>&1; then
        printf '  %-7s ok       (decryptable)\n' "$s"
      else
        printf '  %-7s BROKEN   (present but not decryptable with this key)\n' "$s"
      fi
    else
      printf '  %-7s present  (backend %s — not verified)\n' "$s" "$SECRET_BACKEND"
    fi
  done
  echo "  auth mode: $(auth_mode)"
}

cmd_migrate() {
  [ "${1:-}" = "--yes" ] || die "migrate encrypts legacy plaintext secrets and DESTROYS the plaintext. Re-run with:  secrets.sh migrate --yes"
  need_tools; ensure_key; ensure_sops_yaml
  local moved=0 src dst pair
  # v2.2 plaintext -> v3 scope files. secret.env was the worker credential.
  for pair in "secret.env:worker" "secret.gate.env:gate"; do
    src="$CONFIG_DIR/${pair%%:*}"; dst="$(secret_file "${pair##*:}")"
    [ -f "$src" ] || continue
    [ -f "$dst" ] && { echo "secrets: $dst already exists — skipping $src (delete it yourself once verified)."; continue; }
    ( cd "$CONFIG_DIR" && SOPS_AGE_KEY_FILE="$SOPS_AGE_KEY_FILE" \
        sops encrypt --input-type dotenv --output-type dotenv "$src" > "$dst" )
    # shred is best-effort on journaled/CoW filesystems (ext4-journal/btrfs may keep copies).
    shred -u "$src" 2>/dev/null || rm -f "$src"
    echo "secrets: $src -> $dst (plaintext destroyed; note: on CoW/journaled fs shredding is best-effort)."
    moved=1
  done
  [ "$moved" = 1 ] || echo "secrets: no legacy plaintext files found — nothing to migrate."
}

case "${1:-status}" in
  init)    shift; cmd_init "$@" ;;
  edit)    shift; cmd_edit "$@" ;;
  status)  shift || true; cmd_status ;;
  migrate) shift; cmd_migrate "$@" ;;
  *) die "usage: secrets.sh init [--if-needed] | edit <scope> | status | migrate --yes" ;;
esac
