#!/usr/bin/env bash
# INTERACTIVE SUPERVISION (`loop supervise`) — the human-in-the-loop counterpart of loop.sh.
# You + a strong supervisor Claude (SUPERVISOR_MODEL) decompose, assign, review and land in
# dialogue, while cheap parallel workers (WORKER_MODEL) implement in their worktrees and
# watch.sh auto-runs the gate on every finished burst (semi-auto: landing stays with you).
#
# What it wires (all idempotent):
#   1. the worker pool (spawn.sh wN — herdr panes when a server is up)
#   2. a 'watch' herdr pane running watch.sh (commit-driven gate + feedback routing)
#   3. THIS terminal becomes the supervisor: an interactive Claude with the supervisor
#      playbook (CLAUDE.supervisor.md) as its CLAUDE.md, an isolated CLAUDE_CONFIG_DIR,
#      the host-harness secrets guard, and SUPERVISOR_MODEL — cwd = canonical, so it can
#      author tests/ and run verify.sh / land.sh directly.
#
# Permissions are NOT skipped — you are present, and approving the supervisor's actions is
# the point of this mode. Extra args go straight to claude:  loop supervise -- --continue
#   ./control/supervise.sh [--dry-run] [-- <extra claude args...>]
set -euo pipefail
source "$(dirname "$0")/lib.sh"

DRY_RUN=0; EXTRA_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --) shift; EXTRA_ARGS=("$@"); break ;;
    *) EXTRA_ARGS+=("$1"); shift ;;
  esac
done

[ -d "$CANONICAL/.git" ] || die "canonical not found — run ./control/setup.sh first."
have_credential || die "no credential: run 'claude setup-token' then 'loop secrets edit worker' (or log in to claude on this host)."
command -v claude >/dev/null 2>&1 || die "claude CLI not found on the host."
# Exclusivity: loop.sh auto-assigns and auto-lands — it would fight an interactive supervisor.
if pid="$(heartbeat_pid_alive loop)"; then
  die "loop.sh (pid $pid) is running (full autonomy). Stop it first — supervise and loop.sh must not drive the fleet together."
fi

# 1) Worker pool (idempotent; spawn is herdr-best-effort and works without a server).
mapfile -t WORKERS < <(worker_tasks)
if [ "${#WORKERS[@]}" -eq 0 ]; then
  echo "supervise: bringing up $WORKER_COUNT workers..."
  for i in $(seq 1 "$WORKER_COUNT"); do "$CONTROL_DIR/spawn.sh" "w$i" >/dev/null; done
  mapfile -t WORKERS < <(worker_tasks)
fi

# 2) The gate heartbeat: watch.sh in a herdr pane (it claims watch.pid itself). Without herdr,
#    the operator runs it in a second terminal — auto-backgrounding it here would hide its
#    output and its refusals, so we only instruct.
if [ "$DRY_RUN" = 0 ]; then
  if herdr_ok; then
    if ! herdr agent get watch >/dev/null 2>&1; then
      ws="$(herdr_workspace)"
      herdr agent start watch \
        ${ws:+--workspace "$ws"} \
        --cwd "$ROOT" --no-focus \
        --env "LOOP_PROJECT=$ROOT" \
        -- bash "$CONTROL_DIR/watch.sh" >/dev/null 2>&1 \
        || echo "supervise: could not start the watch pane — run in another terminal: $CONTROL_DIR/watch.sh"
    fi
  else
    if ! heartbeat_pid_alive watch >/dev/null; then
      echo "supervise: herdr not running — start the gate heartbeat yourself: $CONTROL_DIR/watch.sh"
    fi
  fi
fi

# 3) Supervisor Claude config (regenerated each run so engine updates propagate, like spawn.sh).
SCD="$STATE_DIR/supervisor/claude"
mkdir -p "$SCD"
# Playbook + a generated environment appendix (absolute paths — the supervisor never guesses).
{
  cat "$CONTROL_DIR/CLAUDE.supervisor.md"
  cat <<EOF

# Environment (generated by supervise.sh — absolute paths for this workspace)

- Workspace root : $ROOT
- Canonical repo : $CANONICAL   (your cwd; base branch '$BASE_BRANCH' is checked out HERE — workers structurally cannot touch it)
- Control scripts: $CONTROL_DIR   (assign.sh / verify.sh / land.sh / sync.sh / overlap.sh / status.sh / respawn.sh)
- Workers        : ${WORKERS[*]:-(none yet)} — worktrees under $WORKTREES_DIR, branches work/<name>
- Backlog        : $MEMORY_DIR/backlog.md    Progress log: $MEMORY_DIR/PROGRESS.md
- Worker models  : ${WORKER_MODEL:-claude default}   (you run as: ${SUPERVISOR_MODEL:-claude default})
- watch.sh runs the gate automatically on each worker's finished burst and routes failures
  back as feedback — you review PASS notifications and decide: $CONTROL_DIR/land.sh <w>
- Parallel side-work: Claude Code's built-in worktrees (claude -w / subagent isolation) are
  fine for YOUR experiments here in canonical; workers have them hook-blocked and stay boxed.
EOF
} > "$SCD/CLAUDE.md"
# Secrets guard (L2, best-effort — the supervisor is trusted but should not paste keys into
# its own context by accident). Same hook as host-harness, wired by absolute path.
cat > "$SCD/settings.json" <<EOF
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [{ "type": "command", "command": "$CONTROL_DIR/host-harness/harness-guard-secrets" }]
      },
      {
        "matcher": "Read|Edit|Write|MultiEdit|NotebookEdit",
        "hooks": [{ "type": "command", "command": "$CONTROL_DIR/host-harness/harness-guard-secrets" }]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "ExitPlanMode",
        "hooks": [{ "type": "command", "command": "$CONTROL_DIR/host-harness/harness-plan-capture" }]
      }
    ]
  }
}
EOF
# Onboarding pre-seed (only when missing — .claude.json accumulates live session state).
if [ ! -f "$SCD/.claude.json" ]; then
  sed "s|__WORKTREE__|$CANONICAL|g" "$CONTROL_DIR/worker-claude.template.json" > "$SCD/.claude.json"
fi
# Host-login convenience, mirroring spawn.sh.
if ! secret_present worker && [ -f "$HOME/.claude/.credentials.json" ] && [ ! -f "$SCD/.credentials.json" ]; then
  cp "$HOME/.claude/.credentials.json" "$SCD/.credentials.json"
  chmod 600 "$SCD/.credentials.json" 2>/dev/null || true
fi

claude_args=()
[ -n "${SUPERVISOR_MODEL:-}" ] && claude_args+=(--model "$SUPERVISOR_MODEL")
claude_args+=(${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"})

if [ "$DRY_RUN" = 1 ]; then
  echo "supervise dry-run: config at $SCD"
  echo "supervise dry-run: would exec (cwd $CANONICAL): claude ${claude_args[*]:-}"
  exit 0
fi

echo "supervise: workers: ${WORKERS[*]}   watch: gate heartbeat   you: supervisor (${SUPERVISOR_MODEL:-claude default})"
echo "supervise: playbook + environment injected via $SCD/CLAUDE.md — starting Claude in canonical."
cd "$CANONICAL"
export CLAUDE_CONFIG_DIR="$SCD" LOOP_PROJECT="$ROOT" DISABLE_AUTOUPDATER=1
exec_cmd=(claude ${claude_args[@]+"${claude_args[@]}"})
secret_exec worker -- "${exec_cmd[@]}"
